name: api-testing-workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  api-test:
    uses: nelson1234567890/pipeline-reusable-kata/.github/workflows/reusable.yml@master
    with:
        java-version: "22"
        command-execute: "mvn clean verify"
        command-report: "mvn serenity:aggregate"
        path-report: "target/site/serenity"
