name: api-testing-workflow
on:
  push:
    branches:
      - develop
jobs:
  api-test:
    uses: nelson1234567890/pipeline-reusable-kata/.github/workflows/reusable.yml@develop
    with:
        java-version: "22"
        command-execute: "mvn clean verify"
        command-report: "mvn serenity:aggregate"
        path-report: "home/runner/work/kata-api-testing/kata-api-testing/target/site/serenity/index.html"
